import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { readFileSync } from 'node:fs';
import type { SpecDocument } from '@ai-bdd/contracts';
import { parseGaugeSpec } from '@ai-bdd/spec-gauge';
import { parseGherkin } from '@ai-bdd/spec-gherkin';
import { normalizeSpecGlobs } from './globs.js';
import { titleFor } from './titles.js';

export interface GenerateOptions {
  projectRoot: string;
  globs: string[];
  outFile: string;
}

export interface GenerateResult {
  file: string;
  tests: number;
  documents: number;
}

/**
 * Writes the static registration file (VERIFY V2 fallback).
 *
 * V1 confirmed that `e2e/runner` exports only `list`, `ConfigurationError` and
 * `isE2EError`, so a private `run()` cannot be called to drive a project whose
 * specs are discovered at runtime. Projects that need dynamic discovery call
 * `registerSpecs()` at the top level of a collected test file; projects that
 * prefer a reviewable, committed file run this generator instead, and e2e's own
 * runner collects the result exactly like a hand-written test file.
 */
export function generateRegistration(options: GenerateOptions): GenerateResult {
  const documents: SpecDocument[] = [];
  for (const file of normalizeSpecGlobs(options.projectRoot, options.globs)) {
    const text = readFileSync(file, 'utf8');
    const parsed = file.endsWith('.feature') ? parseGherkin(text, file) : parseGaugeSpec(text, file);
    documents.push(parsed.document);
  }

  const titles: Array<{ title: string; steps: Array<{ kind: string; text: string }> }> = [];
  for (const document of documents) {
    for (const scenario of document.scenarios) {
      titles.push({
        title: titleFor(document, scenario),
        steps: scenario.steps.map((step) => ({ kind: step.kind, text: step.text })),
      });
    }
  }

  const lines: string[] = [
    '// Generated by `ai-bdd e2e-host generate` (VERIFY V2 fallback).',
    '// DO NOT EDIT: rerun the generator after changing the specs.',
    '//',
    '// e2e collects tests during module evaluation, so this file is static on purpose.',
    "import { test } from 'e2e';",
    '',
  ];
  for (const entry of titles) {
    lines.push(`test(${JSON.stringify(entry.title)}, { tags: [] }, async ({ agent }) => {`);
    for (const step of entry.steps) {
      if (step.kind === 'action') lines.push(`  await agent.act(${JSON.stringify(step.text)});`);
      else if (step.kind === 'assertion') lines.push(`  await agent.assert(${JSON.stringify(step.text)}, { vision: true });`);
    }
    lines.push('});');
    lines.push('');
  }

  mkdirSync(dirname(options.outFile), { recursive: true });
  writeFileSync(options.outFile, `${lines.join('\n')}\n`);
  return { file: options.outFile, tests: titles.length, documents: documents.length };
}

export function defaultOutFile(projectRoot: string, testsDir = 'tests'): string {
  return join(projectRoot, testsDir, 'ai-bdd.generated.e2e.ts');
}

export function describeOutput(projectRoot: string, file: string): string {
  return relative(projectRoot, file);
}
