packages:
  - 'packages/*'
  - 'plugins/js/*'
  - 'fixtures/*'
  - 'test/*'

allowBuilds:
  esbuild: true
  unrs-resolver: true
  "@rolldown/binding-linux-x64-gnu": true

minimumReleaseAgeExclude:
  - e2e@0.19.0
