/**
 * JSON Schema generation for @ai-bdd/contracts (section 10).
 *
 * The checked-in files under schemas/ are generated by this module; a test
 * asserts that regenerating produces no diff.
 */
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';

import {
  BindingDescriptorSchema,
  DiagnosticSchema,
  SpecDocumentSchema,
  StepSchema,
  StepOptionsSchema,
} from './schemas.js';
import {
  ActProgramSchema,
  CheckProgramSchema,
  LockFileSchema,
  ObservationSchema,
} from './schemas-driver.js';
import {
  EvidenceManifestSchema,
  EvidenceRecordSchema,
  JudgeRequestSchema,
  JudgeVerdictSchema,
  RunReportSchema,
  ScenarioResultSchema,
  StepResultSchema,
} from './schemas-results.js';
import { TOOL_DEFINITIONS } from './tools-table.js';
import { DAEMON_PROTOCOL, TOOL_SHORT_NAMES } from './tools.js';
import { CONFIG_KEYS } from './config.js';
import { ERROR_CODES, type ErrorCodeInfo } from './errors.js';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '..', 'schemas');

const SCHEMAS: Record<string, z.ZodType> = {
  'spec-document': SpecDocumentSchema,
  'step': StepSchema,
  'step-options': StepOptionsSchema,
  'diagnostic': DiagnosticSchema,
  'binding-descriptor': BindingDescriptorSchema,
  'observation': ObservationSchema,
  'act-program': ActProgramSchema,
  'check-program': CheckProgramSchema,
  'lock-file': LockFileSchema,
  'judge-request': JudgeRequestSchema,
  'judge-verdict': JudgeVerdictSchema,
  'evidence-record': EvidenceRecordSchema,
  'evidence-manifest': EvidenceManifestSchema,
  'step-result': StepResultSchema,
  'scenario-result': ScenarioResultSchema,
  'run-report': RunReportSchema,
};

function jsonSchema(schema: z.ZodType, io: 'input' | 'output' = 'output'): unknown {
  return z.toJSONSchema(schema, { target: 'draft-2020-12', io, unrepresentable: 'any' });
}

function write(relative: string, value: unknown): void {
  const target = join(outDir, relative);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

export function generateSchemas(): string[] {
  rmSync(outDir, { recursive: true, force: true });
  const written: string[] = [];
  for (const [name, schema] of Object.entries(SCHEMAS)) {
    write(`${name}.schema.json`, jsonSchema(schema));
    written.push(`${name}.schema.json`);
  }
  for (const tool of TOOL_DEFINITIONS) {
    write(`tools/${tool.short}.input.schema.json`, jsonSchema(tool.input, 'input'));
    write(`tools/${tool.short}.output.schema.json`, jsonSchema(tool.output, 'output'));
    written.push(`tools/${tool.short}.input.schema.json`, `tools/${tool.short}.output.schema.json`);
  }
  write('tools-list.json', {
    protocol: DAEMON_PROTOCOL,
    tools: TOOL_DEFINITIONS.map((tool) => ({
      name: tool.name,
      description: tool.description,
      inputSchema: jsonSchema(tool.input, 'input'),
      outputSchema: jsonSchema(tool.output, 'output'),
      httpPath: tool.path,
    })),
  });
  written.push('tools-list.json');
  write('config-keys.json', { keys: [...CONFIG_KEYS] });
  written.push('config-keys.json');
  write('tool-names.json', { names: TOOL_SHORT_NAMES.map((short) => `aibdd_${short}`) });
  written.push('tool-names.json');
  writeErrorsDoc();
  return written.sort();
}

/** Renders docs/errors.md from ERROR_CODES (section 9.3). */
export function renderErrorsDoc(): string {
  const lines: string[] = [
    '# Error codes',
    '',
    'Generated from `ERROR_CODES` in `@ai-bdd/contracts` by `pnpm -F @ai-bdd/contracts gen:schemas`.',
    'Do not edit by hand; a test asserts this document is in sync with the taxonomy.',
    '',
    '| Code | Group | Retryable | Meaning |',
    '| --- | --- | --- | --- |',
  ];
  const entries = Object.entries(ERROR_CODES) as Array<[string, ErrorCodeInfo]>;
  entries.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  for (const [code, info] of entries) {
    const reserved = info.reserved ? ' (reserved)' : '';
    lines.push(`| \`${code}\` | ${info.group} | ${info.retryable ? 'yes' : 'no'} | ${info.message}${reserved} |`);
  }
  lines.push('');
  return lines.join('\n');
}

export function writeErrorsDoc(): string {
  const target = join(here, '..', '..', '..', 'docs', 'errors.md');
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, renderErrorsDoc(), 'utf8');
  return target;
}
