import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, resolve } from 'node:path';

export interface TestConfigOptions {
  /** Project directory the config file is written into (relative paths below resolve against it). */
  projectDir: string;
  /** File name of the generated config. Default `ai-bdd.config.test.mjs`. */
  fileName?: string;
  /** The project's real config to extend (relative to `projectDir`). `null`: start from an empty config. Default `./ai-bdd.config.mjs`. */
  baseConfig?: string | null;
  /** Directory of fake-model rule files (`*.json`). Absolute, or relative to `projectDir`. */
  rulesDir?: string;
  /** Append every fake model call to this JSONL file. */
  logPath?: string;
  /** Acme feature flags every fake-driver session starts with (`v2`, `bug-upgrade-noop`, ...). */
  flags?: readonly string[];
  /** JSON-serializable settings merged over the base config (`settle`, `characterize`, ...). */
  overrides?: Record<string, unknown>;
}

/**
 * Writes a config file for tests that registers the deterministic fake models and the fake driver through the
 * ordinary pluggable `drivers` / `models` config keys, extending the project's real config. Nothing here is read
 * from the environment and the CLI has no fake mode: a test selects this file with `ai-bdd -c <file>` or
 * `loadConfig({ configPath })`, exactly like a user selects a config that plugs in another driver, such as one built on Cua Driver.
 * Returns the absolute path of the file.
 */
export function writeTestConfig(opts: TestConfigOptions): string {
  const file = resolve(opts.projectDir, opts.fileName ?? 'ai-bdd.config.test.mjs');
  const abs = (p: string): string => (isAbsolute(p) ? p : resolve(opts.projectDir, p));
  const base = opts.baseConfig === undefined ? './ai-bdd.config.mjs' : opts.baseConfig;
  const modelOptions: Record<string, string> = {};
  if (opts.rulesDir !== undefined) modelOptions['rulesDir'] = abs(opts.rulesDir);
  if (opts.logPath !== undefined) modelOptions['logPath'] = abs(opts.logPath);
  const lines = [
    '// Generated by @ai-bdd/testing writeTestConfig: deterministic test doubles plugged in through the normal config keys.',
    "import { createFakeModels, fakeDriver } from '@ai-bdd/testing';",
    ...(base === null ? [] : [`import base from ${JSON.stringify(base)};`]),
    'export default {',
    ...(base === null ? [] : ['  ...base,']),
    ...(opts.overrides === undefined ? [] : [`  ...${JSON.stringify(opts.overrides)},`]),
    `  drivers: { fake: fakeDriver({ flags: ${JSON.stringify([...(opts.flags ?? [])])} }) },`,
    "  defaultDriver: 'fake',",
    `  models: createFakeModels(${JSON.stringify(modelOptions)}),`,
    '};',
    '',
  ];
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, lines.join('\n'));
  return file;
}
